spring:
  jpa:
    open-in-view: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

